### ISSUE TITLE
TypeError: unexpected keyword argument

### ISSUE THREAD

**Issue by wuestenfeld** [tyralla/hydpy#22]
HydPy throws an error while trying to run globwat model. If I delete data = datagrid and init = initgrid from my main file, the model runs. What are the new keywords for the main file?

TypeError: While trying to load the general project settings from `P:\HydPy\examples\danubeGlobWat.py`, the following error occured: __init__() got an unexpected keyword argument 'data'

**Comment by tyralla** [comment]
I finally removed the old global "data timegrid" in commit 2e063f3aac066ad79476fe486faa7b2caf367ad9.  Since each input data series file contains its own "data timegrid", global information on the period and step size of data was no longer required.

A deprecation warning would have been a good idea.  I added it in commit 2e063f3aac066ad79476fe486faa7b2caf367ad9.

The solution is quite simple: just delete the `data` keyword and write e.g. at the top of your working scripts:

```python
from hydpy import *
pub.timegrids = Timegrids(init=Timegrid('2000.11.01 00:00:00',
                                        '2010.11.01 00:00:00',
                                         '1d'),
                          sim=Timegrid('2000.11.01 00:00:00',
                                       '2001.11.01 00:00:00',
                                       '1d'))
````
In this example, ten years will be initialized, of which only the first year will be simulated.  If there is an input data file which does not provide the data for the complete initialization period, an exception will be raised (provided that the `checkseries` option has not been disabled).
